### ISSUE TITLE
Bug: notes with less than five characters fail (ex: "red" "blue")

### ISSUE THREAD

**Issue by jedpimentel** [wadedesir/notes-app#75]
![image](https://github.com/wadedesir/notes-app/assets/6427690/1f3f3915-d3fa-4210-82dc-bef9fa18dc59)

**Comment by MicahMartin** [comment]
this is a feature 
https://github.com/wadedesir/notes-app/blob/690d555471d014753401aec87d9dbe6d34e854af/backend/models/Note.js#L3-L11
